name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-all:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            cross: false
            file-ext: ""
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            cross: false
            file-ext: .exe
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
            cross: true
            file-ext: .exe
          - target: x86_64-apple-darwin
            os: macos-latest
            cross: false
            file-ext: ""
          - target: x86_64-linux-android
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: aarch64-apple-darwin
            os: macos-latest
            cross: true
            file-ext: ""
          - target: aarch64-linux-android
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: aarch64-apple-ios
            os: macos-latest
            cross: true
            file-ext: ""
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: arm-unknown-linux-gnueabi
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: arm-unknown-linux-gnueabihf
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: arm-unknown-linux-musleabi
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: arm-unknown-linux-musleabihf
            os: ubuntu-latest
            cross: true
            file-ext: ""
          - target: armv7-linux-androideabi
            os: ubuntu-latest
            cross: true
            file-ext: ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - name: build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release -p kaminari-cmd --target=${{ matrix.target }}
      - name: pack
        run: |
          mkdir -p build-${{ matrix.target }}
          cd build-${{ matrix.target }}
          tar -C ../target/${{ matrix.target }}/release -zcf kaminari-${{ matrix.target }}.tar.gz kaminaris${{ matrix.file-ext }} kaminaric${{ matrix.file-ext }}
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: kaminari-${{ matrix.target }}.tar.gz
          path: build-${{ matrix.target }}/kaminari-${{ matrix.target }}.tar.gz
